//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PB.rc
//
#define IDC_LB_SESSIONS                 1
#define IDC_LB_MODEMS                   2
#define IDC_LOCAL                       3
#define IDC_REFRESH                     4
#define CM_REFRESH                      4
#define IDC_TB_REFRESH                  5
#define IDC_DISABLE                     6
#define IDC_HANGUP                      7
#define IDC_SHUTDOWN                    8
#define IDM_ABOUTBOX                    0x0010
#define IDC_ABOUT                       0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PBWIN_DIALOG                102
#define CG_IDS_SOCKETS_INIT_FAILED      103
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDR_SESSIONWINDOW               130
#define IDD_PROP_USERED1                134
#define IDD_PROP_USERED_GENERAL         134
#define IDD_PROP_SECURITY               136
#define IDD_PROP_USERED_SECURITY        136
#define IDD_SECLEVELS                   137
#define IDD_EDIT_SECLEVEL               138
#define IDD_PROP_OPT_DIRECTORIES        139
#define IDD_PROP_OPT_SECURITY           140
#define IDD_PROP_OPT_NEWUSERS           141
#define IDD_PROP_OPT_SITEINFO           144
#define IDD_MSGAREA                     145
#define IDD_AREAS                       146
#define IDC_NAME                        1000
#define IDC_ALIAS                       1001
#define IDC_NAME2                       1002
#define IDC_ALIAS2                      1003
#define IDC_NAME3                       1004
#define IDC_ALIAS3                      1005
#define IDC_NAME4                       1006
#define IDC_COMBO1                      1007
#define IDC_NAME5                       1008
#define IDC_ALIAS4                      1009
#define IDC_NAME6                       1010
#define IDC_ALIAS5                      1011
#define IDC_LISTUSERS                   1012
#define IDC_LEVEL                       1013
#define IDC_DATEFMT                     1014
#define IDC_EXPLEVEL                    1014
#define IDC_EDIT1                       1015
#define IDC_LEVELS                      1016
#define IDC_DESCRIPTION                 1016
#define IDC_ED_FILELOCATION             1016
#define IDC_EDIT                        1017
#define IDC_ED_CATALOGFILE              1017
#define IDC_NEW                         1018
#define IDC_DELETE                      1019
#define IDC_SPIN1                       1024
#define IDC_EXPDATE_DAY                 1025
#define IDC_EXPDATE_MONTH               1028
#define IDC_EXPDATE_YEAR                1030
#define IDC_ED_MSGBASE                  1031
#define IDC_ED_PEX                      1032
#define IDC_AVATAR                      1033
#define IDC_ED_PEX2                     1034
#define IDC_ED_MENUS                    1034
#define IDC_ANSI                        1035
#define IDC_ED_PEX3                     1036
#define IDC_ED_TXTFILES                 1036
#define IDC_ASKVOICE                    1037
#define IDC_ASKDATAPHONE                1038
#define IDC_ASKFAXPHONE                 1039
#define IDC_ASKBIRTHDATE                1040
#define IDC_ASKSTATE                    1041
#define IDC_ASKCOUNTRY                  1042
#define IDC_ASKADDRESS                  1043
#define IDC_ASKSEX                      1044
#define IDC_ASKDATEFMT                  1045
#define IDC_LOGLEVEL                    1046
#define IDC_USESYSTEMPWD                1048
#define IDC_ED_BROW_MSGBASE             1049
#define IDC_ED_BROW_MSGBASE2            1050
#define IDC_EDIT_BBSNAME                1053
#define IDC_EDIT_SYSOPNAME              1054
#define IDC_ED_AREANAME                 1054
#define IDC_EDIT_LOCATION               1055
#define IDC_LISTBOX                     1055
#define IDC_EDIT_ORIGINLINE             1056
#define IDC_FLAGEDITCTRL1               1062
#define IDM_HANGUP                      32772
#define IDM_FONT                        32773
#define IDM_MINIMIZE                    32774
#define IDM_INFRONT                     32775
#define IDM_ABOUT                       32776
#define IDM_SHOWUSERINFO                32777
#define IDM_SHOWLOGWINDOW               32779
#define ID_CONFIGURATION_FILEAREAS      32780
#define IDM_FILEAREAS                   32780
#define ID_CONFIGURATION_MESSAGEAREAS   32781
#define IDM_MSGAREAS                    32781
#define ID_CONFIGURATION_OPTIONS        32782
#define IDM_USERS                       32783
#define ID_CONFIGURATION_FILETRANSFERPROTOCOLS 32784
#define IDM_PROTOCOLS                   32784
#define ID_CONFIGURATION_LIMITS         32785
#define ID_CONFIGURATION_MENUS          32786
#define IDM_MENUS                       32786
#define ID_CONFIGURATION_MACROS         32787
#define IDM_MACROS                      32787
#define ID_CONFIGURATION_EVENTS         32788
#define IDM_EVENTS                      32788
#define ID_CONFIGURATION_LANGUAGES      32789
#define IDM_LANGUAGES                   32789
#define ID_CONFIGURATION_MODEMS         32790
#define IDM_MODEMS                      32790
#define ID_CONFIGURATION_TCPIP          32791
#define IDM_TCPIP                       32791
#define IDM_LEVELS                      32792
#define IDM_OPT_DIRS                    32793
#define IDM_OPT_NEWUSERS                32794
#define IDM_OPT_SECURITY                32795
#define IDM_SITEINFO                    32796
#define IDM_PAGING                      32797

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32798
#define _APS_NEXT_CONTROL_VALUE         1069
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
