//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PBWin.rc
//
#define IDC_LB_SESSIONS                 1
#define IDC_LB_MODEMS                   2
#define IDC_LOCAL                       3
#define IDC_REFRESH                     4
#define CM_REFRESH                      4
#define IDC_TB_REFRESH                  5
#define IDC_DISABLE                     6
#define IDC_HANGUP                      7
#define IDC_SHUTDOWN                    8
#define IDM_ABOUTBOX                    0x0010
#define IDC_ABOUT                       0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PBWIN_DIALOG                102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDR_SESSIONWINDOW               130
#define IDD_PROP_USERED1                134
#define IDD_PROP_SECURITY               136
#define IDD_SECLEVELS                   137
#define IDD_EDIT_SECLEVEL               138
#define IDC_NAME                        1000
#define IDC_ALIAS                       1001
#define IDC_NAME2                       1002
#define IDC_ALIAS2                      1003
#define IDC_NAME3                       1004
#define IDC_ALIAS3                      1005
#define IDC_NAME4                       1006
#define IDC_COMBO1                      1007
#define IDC_NAME5                       1008
#define IDC_ALIAS4                      1009
#define IDC_NAME6                       1010
#define IDC_ALIAS5                      1011
#define IDC_LISTUSERS                   1012
#define IDC_LEVEL                       1013
#define IDC_DATEFMT                     1014
#define IDC_EXPLEVEL                    1014
#define IDC_EDIT1                       1015
#define IDC_LEVELS                      1016
#define IDC_DESCRIPTION                 1016
#define IDC_EDIT                        1017
#define IDC_NEW                         1018
#define IDC_DELETE                      1019
#define IDC_SPIN1                       1024
#define IDC_EXPDATE_DAY                 1025
#define IDC_EXPDATE_MONTH               1028
#define IDC_EXPDATE_YEAR                1030
#define IDM_HANGUP                      32772
#define IDM_FONT                        32773
#define IDM_MINIMIZE                    32774
#define IDM_INFRONT                     32775
#define IDM_ABOUT                       32776
#define IDM_SHOWUSERINFO                32777
#define IDM_SHOWLOGWINDOW               32779
#define ID_CONFIGURATION_FILEAREAS      32780
#define ID_CONFIGURATION_MESSAGEAREAS   32781
#define ID_CONFIGURATION_OPTIONS        32782
#define IDM_USERS                       32783
#define ID_CONFIGURATION_FILETRANSFERPROTOCOLS 32784
#define ID_CONFIGURATION_LIMITS         32785
#define ID_CONFIGURATION_MENUS          32786
#define ID_CONFIGURATION_MACROS         32787
#define ID_CONFIGURATION_EVENTS         32788
#define ID_CONFIGURATION_LANGUAGES      32789
#define ID_CONFIGURATION_MODEMS         32790
#define ID_CONFIGURATION_TCPIP          32791
#define IDM_LEVELS                      32792

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
